"""
AI Operations Assistant
Workflow Storage Module

PURPOSE
-------
This module manages persistent workflow storage.

The workflow engine in app.py creates Python dictionaries containing
workflow and task information. Those dictionaries exist only in memory
while the application is running.

This module allows workflows to be:

1. Converted to JSON
2. Saved to disk
3. Loaded during future application sessions

WHY JSON?
---------
JSON (JavaScript Object Notation) is widely used for structured data.

It is useful here because Python dictionaries translate naturally
into JSON objects.

JSON also prepares the application for future integrations with:

- Web applications
- REST APIs
- Databases
- Automation platforms
- AI services
"""

import json
from pathlib import Path


# ===========================================================================
# STORAGE CONFIGURATION
# ===========================================================================

# Determine the directory containing this Python file.
BASE_DIR = Path(__file__).resolve().parent

# Store application-generated data separately from source code.
DATA_DIR = BASE_DIR / "data"

# Main workflow storage file.
WORKFLOW_FILE = DATA_DIR / "workflows.json"


# ===========================================================================
# STORAGE INITIALIZATION
# ===========================================================================

def initialize_storage():
    """
    Create the application's data directory and workflow file if needed.

    exist_ok=True prevents an error when the directory already exists.

    The initial JSON structure is an empty list because the application
    will eventually store multiple workflow objects.
    """

    DATA_DIR.mkdir(exist_ok=True)

    if not WORKFLOW_FILE.exists():
        with WORKFLOW_FILE.open("w", encoding="utf-8") as file:
            json.dump([], file, indent=4)


# ===========================================================================
# LOAD WORKFLOWS
# ===========================================================================

def load_workflows():
    """
    Load all previously saved workflows.

    Returns
    -------
    list
        List containing saved workflow dictionaries.

    ERROR HANDLING
    --------------
    If the JSON file becomes empty or invalid, JSON decoding would normally
    crash the program.

    For this early version, the application safely returns an empty list.
    """

    initialize_storage()

    try:
        with WORKFLOW_FILE.open("r", encoding="utf-8") as file:
            return json.load(file)

    except json.JSONDecodeError:
        return []


# ===========================================================================
# SAVE WORKFLOW
# ===========================================================================

def save_workflow(workflow):
    """
    Add a workflow to persistent storage.

    Process
    -------
    1. Load existing workflows.
    2. Add the new workflow.
    3. Write the complete collection back to the JSON file.

    Parameters
    ----------
    workflow : dict
        Structured workflow generated by the workflow engine.
    """

    workflows = load_workflows()

    workflows.append(workflow)

    with WORKFLOW_FILE.open("w", encoding="utf-8") as file:
        json.dump(
            workflows,
            file,
            indent=4,
            ensure_ascii=False,
        )


# ===========================================================================
# WORKFLOW COUNT
# ===========================================================================

def count_workflows():
    """
    Return the number of workflows currently stored.

    This small helper will later be useful for dashboard metrics.
    """

    return len(load_workflows())